version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
      - type: bind
        source: ./dump
        target: /dump/
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel
  backup_restoration:
    image: dgraph/dgraph:latest
    command: dgraph live -r /dump/g01.rdf.gz -s /dump/g01.schema.gz -z zero:5080 -d server:9080
    restart: on-failure
    volumes:
      - type: bind
        source: ./dump
        target: /dump/
    depends_on:
      - server
      - zero

volumes:
  dgraph:
